from extractor import gen

gen("Possible incriminating evidence: \n\n1. Mean: Godefroi had the opportunity to steal the Robe of the Saints when he unlocked the chest and replaced the robes. He could have taken the valuable robe and replaced it with a less valuable one.\n2. Motive: Godefroi might have been tempted by the value of the Robe of the Saints, hoping to sell it for personal gain.\n3. Opportunity: Godefroi was responsible for guarding the chest, which gave him exclusive access to it. He could have taken the robe while everyone was asleep and replaced it with a less valuable one.\nBased on what precedes, is there incriminating evidence for Godefroi? Answer with Yes or No.", ['No', 'Yes'])

gen("Possible incriminating evidence: \n\n1. Mean: Godefroi had the opportunity to steal the Robe of the Saints when he unlocked the chest and replaced the robes. He could have taken the valuable robe and replaced it with a less valuable one.\n2. Motive: Godefroi might have been tempted by the value of the Robe of the Saints, hoping to sell it for personal gain.\n3. Opportunity: Godefroi was responsible for guarding the chest, which gave him exclusive access to it. He could have taken the robe while everyone was asleep and replaced it with a less valuable one.\n\nEvidence for Godefroi's guilt:\n\n1. Godefroi had the opportunity to steal the Robe of the Saints when he unlocked the chest and replaced the robes.\n2. Godefroi'\nBased on what precedes, is there incriminating evidence for Godefroi? Answer with Yes or No.", ['No', 'Yes'])

gen("Possible incriminating evidence: \n\n1. Mean: Godefroi had the opportunity to steal the Robe of the Saints when he unlocked the chest and replaced the robes. He could have taken the valuable robe and replaced it with a less valuable one.\n2. Motive: Godefroi might have been tempted by the value of the Robe of the Saints, hoping to sell it for personal gain.\n3. Opportunity: Godefroi was responsible for guarding the chest, which gave him exclusive access to it. He could have taken the robe while everyone was asleep and replaced it with a less valuable one.\n\nEvidence for Godefroi's guilt:\n\n1. Godefroi had the opportunity to steal the Robe of the Saints when he unlocked the chest and replaced the robes.\n2. Godefroi'\nIs there incriminating evidence for Godefroi? Answer with Yes or No.", ['No', 'Yes'])

gen("Possible incriminating evidence: \n\n1. Mean: Godefroi had the opportunity to steal the Robe of the Saints when he unlocked the chest and replaced the robes. He could have taken the valuable robe and replaced it with a less valuable one.\n2. Motive: Godefroi might have been tempted by the value of the Robe of the Saints, hoping to sell it for personal gain.\n3. Opportunity: Godefroi was responsible for guarding the chest, which gave him exclusive access to it. He could have taken the robe while everyone was asleep and replaced it with a less valuable one.\n\nEvidence for Godefroi's guilt:\n\n1. Godefroi had the opportunity to steal the Robe of the Saints when he unlocked the chest and replaced the robes.\n2. Godefroi'\nIs there strong incriminating evidence for Godefroi? Answer with Yes or No.", ['No', 'Yes'])
